name: av2
channels:
  - conda-forge
dependencies:
  - av
  - click
  - joblib
  - k3d
  - matplotlib-base
  - nox
  - numba
  - numpy>=1.21.5
  - opencv
  - pandas
  - pip
  - pyarrow
  - pyproj
  - rich
  - scipy
