name: av2
channels:
  - conda-forge
dependencies:
  - av
  - click
  - joblib
  - matplotlib-base
  - maturin
  - nox
  - numba
  - numpy
  - opencv
  - pandas
  - pip
  - polars
  - pyarrow
  - pyproj
  - rich
  - rust
  - scipy
  - pytorch
  - universal_pathlib
