[package]
name = "av2"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "av2"
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.66"
argminmax = { version = "0.6.1", features = ["ndarray"] }
bincode = "1.3.3"
glob = "0.3.1"
# image = { git = "https://github.com/Shnatsel/image", branch = "zune-jpeg-sneaky" }
image = "0.24.6"
ignore = "0.4.20"
itertools = "0.10.5"
ndarray = { version = "0.15.6", features = [
    "matrixmultiply-threading",
    "rayon",
] }
nshare = { version = "0.9.0", features = ["ndarray"] }
numpy = { version = "0.18.0" }
once_cell = "1.17.1"
polars = { version = "0.28.0", features = [
    "asof_join",
    "dtype-u8",
    "dtype-u16",
    "lazy",
    "ndarray",
    "parquet",
    "ipc",
    "serde",
    "serde-lazy",
] }
pyo3 = { version = "0.18.3", features = ["extension-module"] }
pyo3-polars = { git = "https://github.com/benjaminrwilson/pyo3-polars", rev = "993d22a6bf54ceb8f93c5ed9082621330b186a52", features = [
    "serde",
] }
rayon = "1.7.0"
serde = "1.0.160"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
