name: CI

on: [push, pull_request]

jobs:
  test_and_build:
    name: ${{ matrix.os }}_${{ matrix.venv_backend }}_py${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python_version:
          ["3.8", "3.9", "3.10"]
        venv_backend:
          ["mamba", "virtualenv"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Reclaim space.
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: av2
          environment-file: conda/environment.yml
          mamba-version: "*"
          miniforge-version: latest
          python-version: ${{ matrix.python_version }}

      - name: Install prerequisites.
        run: |
          mamba install -y pip

      - name: Run nox with ${{ matrix.venv_backend }}.
        run: >-
          maturin develop --extras test

      - name: Run CI.
        run: |
          black .
          isort .
          flake8 .
          mypy .
          "pytest" "tests" "--cov" "src/av2"

      - name: Install pypa/build.
        run: >-
          python -m
          pip install
          build
          --user
          
      - name: Build a binary wheel and a source tarball.
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
